/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package final_report;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class LuffyTest {
    @Test
    void otameshi() {
        Luffy Monkey_D_Luffy = new Luffy("モンキー・D・ルフィ","「麦わら」",3000,0,5000,700,600,400,"ゴムゴムのJET銃!","ゴムゴムのJETバズーカ!","ゴムゴムの巨人の銃!");
        Enemy Rucchi = new Enemy("ロブ・ルッチ","CP9 「殺戮兵器」",0,6000,600,650,400,"死銃","嵐脚「凱鳥」","死銃「斑」","最大輪「六王銃」");
        Monkey_D_Luffy.showStatus();
    }
}